---
# Install ganglia-monitor in RedHat

- name: Install ganglia-monitor
  yum: name={{ item }} enablerepo=* state=latest
  with_items:
    - rrdtool
    - ganglia-gmetad
    - ganglia-web
    - ganglia
  notify: Start ganglia-monitor